// Code generated by mockery v2.40.1. DO NOT EDIT.

package client

import (
	context "context"

	entities "github.com/qrinef/process-app/pkg/api/entities"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockExternal is an autogenerated mock type for the externalService type
type MockExternal struct {
	mock.Mock
}

type MockExternal_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExternal) EXPECT() *MockExternal_Expecter {
	return &MockExternal_Expecter{mock: &_m.Mock}
}

// GetLimits provides a mock function with given fields:
func (_m *MockExternal) GetLimits() (uint64, time.Duration) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLimits")
	}

	var r0 uint64
	var r1 time.Duration
	if rf, ok := ret.Get(0).(func() (uint64, time.Duration)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func() time.Duration); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(time.Duration)
	}

	return r0, r1
}

// MockExternal_GetLimits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLimits'
type MockExternal_GetLimits_Call struct {
	*mock.Call
}

// GetLimits is a helper method to define mock.On call
func (_e *MockExternal_Expecter) GetLimits() *MockExternal_GetLimits_Call {
	return &MockExternal_GetLimits_Call{Call: _e.mock.On("GetLimits")}
}

func (_c *MockExternal_GetLimits_Call) Run(run func()) *MockExternal_GetLimits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockExternal_GetLimits_Call) Return(n uint64, p time.Duration) *MockExternal_GetLimits_Call {
	_c.Call.Return(n, p)
	return _c
}

func (_c *MockExternal_GetLimits_Call) RunAndReturn(run func() (uint64, time.Duration)) *MockExternal_GetLimits_Call {
	_c.Call.Return(run)
	return _c
}

// Process provides a mock function with given fields: ctx, batch
func (_m *MockExternal) Process(ctx context.Context, batch entities.Batch) error {
	ret := _m.Called(ctx, batch)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Batch) error); ok {
		r0 = rf(ctx, batch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExternal_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type MockExternal_Process_Call struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - ctx context.Context
//   - batch entities.Batch
func (_e *MockExternal_Expecter) Process(ctx interface{}, batch interface{}) *MockExternal_Process_Call {
	return &MockExternal_Process_Call{Call: _e.mock.On("Process", ctx, batch)}
}

func (_c *MockExternal_Process_Call) Run(run func(ctx context.Context, batch entities.Batch)) *MockExternal_Process_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.Batch))
	})
	return _c
}

func (_c *MockExternal_Process_Call) Return(_a0 error) *MockExternal_Process_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExternal_Process_Call) RunAndReturn(run func(context.Context, entities.Batch) error) *MockExternal_Process_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExternal creates a new instance of MockExternal. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExternal(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExternal {
	mock := &MockExternal{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
